device: "auto"
train: # metrics that are calculated during training
  - _target_: src.metrics.MSEMetric
    name: "MSE"
  - _target_: src.metrics.RVQPerplexityMetric
    name: "Perplexity"
    codebook_size: ${generator.model.codebook_size}
    normalized: true
inference: # metrics that are calculated during inference (eval)
  - _target_: src.metrics.MSEMetric
    name: "MSE"
  - _target_: src.metrics.STOIMetric
    name: "STOI"
  - _target_: src.metrics.NISQAMOSMetric
    name: "NISQA_MOS"
