defaults:
  - generator: soundstream
  - discriminator: soundstream
  - writer: cometml
  - metrics: baseline
  - datasets: libri_speech
  - dataloader: basic
  - transforms: basic
  - _self_

writer:
  run_name: "adv_finetuning"

generator:
  loss_function:
    commitment_loss_weight: 2
    multiscale_reconstruction_loss_weight: 0.01

trainer:
#  generator_max_grad_norm: 10000
#  discriminator_max_grad_norm: 10000

  log_step: 100
  n_epochs: 20
  epoch_len: 2000
  device_tensors: ["audio"] # which tensors should be on device (ex. GPU)
  resume_from: null # null or path to the checkpoint dir with *.pth and config.yaml
  from_pretrained: "saved/train/checkpoint-epoch12-24000.pth"
  load_discriminator: True
  device: auto # device name or "auto"
  override: True # if True, will override the previous run with the same name
#  monitor: "max test_MulticlassAccuracy" # "off" or "max/min metric_name", i.e. our goal is to maximize/minimize metric
  save_period: 1 # checkpoint each save_period epochs in addition to the best epoch
  early_stop: ${trainer.n_epochs} # epochs for early stopping
  save_dir: "saved"
  seed: 1
  log_mel:
    win_length: 1024
    hop_length: 256
    n_mels: 64
