defaults:
  - generator: soundstream
  - metrics: baseline
  - datasets: libri_speech_inference # we do not want to run inference on training data
  - dataloader: basic
  - transforms: basic
  - _self_
inferencer:
  device_tensors: ["audio"] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  save_path: "example" # any name here, can be a dataset name
  seed: 1
  from_pretrained: "saved/soundstream_generator.pth" # path to the pretrained model
