train:
  _target_: torch.utils.data.DataLoader
  batch_size: 12
  num_workers: 2
  pin_memory: True
  persistent_workers: True

inference:
  _target_: torch.utils.data.DataLoader
  batch_size: 24
  num_workers: 2
  pin_memory: True
  persistent_workers: True
